updates to docker image osx-arm64 packages revert broken embedpy under python commit compiler warnings remove tensorflow tests restrict to python 3.9 and 3.10 retry numpy import on osx due to warnings generated in more recent versions of numpy
 RuntimeError: Polyfit sanity test emitted a warning, most likely due to using a buggy Accelerate backend.
    If you compiled yourself, more information is available at:
    https://numpy.org/doc/stable/user/building.html#accelerated-blas-lapack-libraries
    Otherwise report this to the vendor that provided NumPy.